### PR TITLE
Portuguese (pt_PT) update

### PR DESCRIPTION
**Pull request by pedro-mendonca**

### CODE REVIEW

**Comment by Lorti** [comment]
Reminds me that I should update the german language pack as well 😄

**Comment by pedro-mendonca** [comment]
And the .pot :)
I'll keep pushing the translation here, unless you want it just on the wordpress repo, where I'm also pushing the same translation. I like to keep local translations updated as a way of debug them on the fly, much faster than the workflow of the language packs.

**Comment by Lorti** [comment]
Since this is a tedious process and WordPress will eventually be moving all i18n to translate.wordpress.org I will remove the languages folder from the plugin.

**Comment by pedro-mendonca** [comment]
Ok :+1:

**Pull request merged**
